### ISSUE TITLE
Timer Pauses When Switching Tabs

### ISSUE THREAD

**Issue by yossev** [yossev/KittyDoro#4]

**Comment by yousefnegmeldin** [comment]
this works now

**Comment by yossev** [comment]
> this works now

How was it fixed? Doesnt it have to do with Chrome pausing JS Excution to save performance?

**Comment by yousefnegmeldin** [comment]
i didnt touch the code for this part i guess it was a fault from your browser or environment

**Comment by yossev** [comment]
> i didnt touch the code for this part i guess it was a fault from your browser or environment

I Searched up the issue , it was most likely some power-saving mechanism in the Browser itself.
Thanks!
